### ISSUE TITLE
Pocket operation fails for non-convex shapes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [swarfer/sketchucam#1]
```
Create a non-convex shape with a need for at least two distinct paths.

Pocket operation generates a paths for only a part of the face.



```

Original issue reported on code.google.com by `szymansk...@gmail.com` on 27 Feb 2014 at 4:43

Attachments:
- [Screen Shot 2014-02-26 at 8.42.03 PM.png](https://storage.googleapis.com/google-code-attachments/sketchucam/issue-1/comment-0/Screen Shot 2014-02-26 at 8.42.03 PM.png)

**Comment by swarfer** [comment]
This has mostly been addressed by the FLOOD pocket method.
