### ISSUE TITLE
outside cuts with tiny circles causes crashes

### ISSUE THREAD

**Issue by Dloranger** [swarfer/sketchucam#10]
all settings are still defualt as I just reloaded moments ago.  To create the crash, draw a circle smaller than your tool.  Try to use the outside cut tool.  Sketchup (2017) will lock up immediately even upon hovering over the circle, force close is the only escape I have found

**Comment by swarfer** [comment]
I cannot reproduce this.  I have tried a 6mm bit with various circles down to 0.5mm radius, anything smaller produces an error message from Sketchup that the radius is too small..

Please tell me more information.
bit diameter
circle size
circle segments
does the circle stand alone or is it part of another shape
model units?  should NOT be fractional inches, decimal is ok (this is because of accuracy limits within Sketchup and the way it rounds to the next or previous fraction).

Please attach your file here so I can open it.

**Comment by Dloranger** [comment]
![image](https://user-images.githubusercontent.com/10390925/67685410-44e4f180-f952-11e9-9c9c-11a4f1ba1271.png)

these settings works on the small dsub-9 connector mounting screw holes.

however only changing the bit size to 0.135", sketchup completely freezes and I have to force close it

![image](https://user-images.githubusercontent.com/10390925/67685692-cccafb80-f952-11e9-848e-451edf2a7c2b.png)


![image](https://user-images.githubusercontent.com/10390925/67685883-161b4b00-f953-11e9-8c3a-f49391ca667e.png)

Processor that is being used by sketchup is maxed out and the fan on the laptop goes to full power so something is definetely working hard in the background

![image](https://user-images.githubusercontent.com/10390925/67686160-84f8a400-f953-11e9-85fd-d1433dca0220.png)

[case-rev1-cutout-template.zip](https://github.com/swarfer/sketchucam/files/3779093/case-rev1-cutout-template.zip)

**Comment by Dloranger** [comment]
interesting side observation, it looks like internet explorer is trying to do something in the background as well that is also pegging the processor(s), I never use internet explorer so there shouldn't be anything there that I would have launched or have running.    

This did not repeat when I forced it to close as well (note it was only a background task, nothing visible to the user) and this also drastically helps the thermals as the fans also drop power noticeably.

When I kill sketchup, iexplorer.exe drops to 0% processor usage as well.

![image](https://user-images.githubusercontent.com/10390925/67686730-647d1980-f954-11e9-885b-b74ef0d98bd7.png)

Having sketchup running with the model loaded, everything is still happy
![image](https://user-images.githubusercontent.com/10390925/67686909-a9a14b80-f954-11e9-8911-e8757b63dc7b.png)

Having forced the crash, I see sketchup immediately jump up to full processor loading

![image](https://user-images.githubusercontent.com/10390925/67687048-ea00c980-f954-11e9-963b-8ee9517f3fb7.png)

**Comment by swarfer** [comment]
you have a 3D drawing AND your face is therefore reversed (white).   The face must be blue, and the outside cut tool must cut OUTSIDE ,  no wonder I could not reproduce the problem, you are doing an outside cut to cut inside a circle which I would never even try.

The first thing to do is phlatten it and make sure all hidden lines that are not on the XY plane are removed:
select the entire drawing, right click, select 'Phlat Edge | Phlatten selected edges'
(and I see many doubled lines as though the top and bottom surfaces of your 3D model did not line up, remove those too, or remove the back face before phlattening)

you do realize that 0.135" is larger than most of those 0.089" holes , right (-: ?
There is no way it can find an inside cut for that.
The correct way to make a hole is with the plunge hole tool, it uses a spiral feed that is much better for the tool in small spaces like that and also gives proper round holes.
http://swarfer.github.io/sketchucam/sketchucamtoolbar.html#toolplunge

here is a fixed version of your file
[case-rev1-cutout-template.zip](https://github.com/swarfer/sketchucam/files/3779405/case-rev1-cutout-template.zip)

Please watch these (knowledge is power!  you can read the manual too for extra power :) )
https://www.youtube.com/playlist?list=PLm728rLHCWOw-vRvTJwS_5MmKG1fs4sZ0

**Comment by swarfer** [comment]
**do not** cut the .cnc file I provided, you still need to add tabs to those inside cuts unless you are using the masking tape and superglue holddown method which will _probably_ prevent the loose bits from jamming and breaking the tool.

**Comment by Dloranger** [comment]
I will try to get this all digested in the next couple days.  Thanks for the feedback.

Might be good to problematically block this bad behavior if possible to prevent people like me with bad models from crashing the tool.  I love the tool, but I have also cursed it as well as I have ran into this issue for several years and finally figured out how to work around it.  This is the first time I have found the tools in github to be able to feedback the challenge I seemingly recreate frequently over the years.

**Comment by Dloranger** [comment]
also for the oversized bit vs the 0.089 holes, lol, yes I do realize this is the case, but I have encountered this issue several times due to accidentally traveling over a small feature when trying to move to a larger feature.  Gets annoying having to hit save after each feature is treated just in case I accidently had an errant mouse movement.

**Comment by swarfer** [comment]
Please install this and test.
[SketchUcam-1_5-da07c6c.zip](https://github.com/swarfer/sketchucam/files/3782355/SketchUcam-1_5-da07c6c.zip)
after you download the file change the extension to 'rbz' instead of 'zip' so that Sketchup recognizes it as an installer.

Please join us on the forums at http://openbuilds.com for all the help you will ever need (but do read the manual first, it really will help you!  click the big blue question mark in the toolbar)
