### ISSUE TITLE
G53 issue

### ISSUE THREAD

**Issue by phil-barrett** [swarfer/sketchucam#11]
In the latest SKUC, a G53 G00 Z0.0 is output in the GCode preamble and postamble.  I want to turn that off.  I've hacked GCodeUtil and PhlatMill to remove G53 line generation. In a future release, it would be good to make that an option.

And, it would be good to have a way to configure more of the preamble/postamble code but I suspect that's not very likely to happen.

Thanks
Phil

**Comment by swarfer** [comment]
The use of G53 is not an issue, it is an industry safety standard.
You have the option of changing the offset so it does not trigger a limit switch.
If a G53 G0 Z0 still interferes with how you are using your machine then maybe you are doing something wrong?

If you have limit switches then homing with Z high is perfect.
If you have no switches then resetting the controller with Z high 'fakes the home'.
Once you have a good Z home, G53 moves are safe and 'do the right thing' everytime.
