### ISSUE TITLE
Layers

### ISSUE THREAD

**Issue by phil-barrett** [swarfer/sketchucam#7]
Not necessarily a problem. I posted some of this on OpenBuilds but thought it might be better here.

Layers work but it would be really cool with one change. Currently it appears that all layers are used to generate GCode, even ones with "Visible" unchecked. This is a bit of a departure from Sketchup - you can't select things on non visible layers. If only visible layers were used to generate GCode, then we could use this to separate out pieces of a design for different treatment. I'm probably naive to think that it's as simple as a check to see if visible when generating code for a given object. 

This could make for some interesting enhancements:
- attach different parameters to a give layer
- tool change. put all the cuts with given tool on a different layer

**Comment by swarfer** [comment]
I had a look.  at first it seems simple, ignore entities where
entities.layer.visible? is false.
However this works only for simple objects and completely breaks the group processing.
Also we must never forget that Sketchup layers, whether visible or not, always intersect with all other layers.  This too will cause unforseen issues.
Ergo, this will not make it into the 'very soon now' 1.5 release but may be usable in some future release as it would be useful and provides and alternate mode of working to the multiple drawings method I use all the time.

**Comment by phil-barrett** [comment]
Yeah, I played with a bunch more and, like any "good" idea with minimal investigation, it became clear there were just too many problems with it. Thanks for looking anyway.
