### ISSUE TITLE
Hole boring GCode generation problem.

### ISSUE THREAD

**Issue by phil-barrett** [swarfer/sketchucam#8]
Small part. Using a 1/8"(3.175mm) end mill, I wanted to bore 2 4.1mm and 1 6.6mm holes.  It appears to be correctly boring the 6.6mm hole but the two 4.1 holes are being doubled with the extra holes 1/2 diameter to the outside of the correct location.  It appears that the finishing pass (if that's what it is supposed to be) is being mispositioned.  At first I thought the GCode Plotter was misreporting but, nope. it generate 2 holes - see the photo of the part I cut.

SketchUcam V1.4d-80c0152
Included in the zip file: sku model, cnc code, photo and saved .tpi file.  
Let me know if you need anything else.

[hole boring problem.zip](https://github.com/swarfer/sketchucam/files/3511692/hole.boring.problem.zip)

**Comment by swarfer** [comment]
Lines that cross the purple line in the plunge hole symbol will cause this, it is well known and mentioned in the help.
This is why holes are created as groups, which helps most of the time.
Maybe you can select the underlying lines and create a group out of them?

**Comment by phil-barrett** [comment]
Thanks.  My lines aren't purple (brown for large holes) but removing the circles from the model fixed the problem. I misunderstood the "horizontal line" comment in the help.  Probably easier to just say no lines, circles or arcs where the hole cut is placed.  Makes me wonder about how to annotate my model so I get hole locations correct.

[edit] 3/4 of a cross hair does the trick for annotating[/edit]

**Comment by swarfer** [comment]
ah, how can I rewrite that bit of help so it is clear?

I draw a little triangle with the top right corner at the center point.  The triangle usually fits within the hole.

**Comment by phil-barrett** [comment]
Sometimes I'm a bit slow to process things.  The thing that probably confused me is the intersecting thing and the distinction between model objects and CNC objects.  Maybe just say no lines where the cut symbol will go.  

Thinking on it, making a group out of the model's holes is pretty clean.  Gives me thoughts to just make the flattened parts a group and redraw cut lines on top of that. will try that on my next project.

Thanks again for listening to me ramble.
