### ISSUE TITLE
Narrow slot issue

### ISSUE THREAD

**Issue by phil-barrett** [swarfer/sketchucam#9]
[sucam narrow slot issue.zip](https://github.com/swarfer/sketchucam/files/3511730/sucam.narrow.slot.issue.zip)
If you create a slot via an outside cut that is wider than the cutting tool width by a very small amount suCAM will not generate GCode.  In the example, I show a 3.175mm bit and 2 slots, one 3.2mm wide and another 3.225mm wide.  The 3.225mm slot has GCode generated, the 3.2mm doesn't.  So, a slot must be wider than the bit by somewhere between .025 and .050mm. The workaround is to either slightly widen the slot or separately use the centerline tool for end mill width slots.  SUCAM shows the cut in the slot.

By the way, you don't need to actually generate GCode to see if the problem exists.  If you use the SUCAM eraser tool, it leaves the cut outline in the slot that won't get GCode generated. It's a useful quick check to see if there is a problem.

I'm pretty sure this is a sketchup problem as it generally makes a mess of anything with small dimensions. I think SUCAM should recognize this situation and refuse to show the line in the slot that is too narrow.

**Comment by swarfer** [comment]
This is entirely due to Sketchup's internal comparison operator which considers A to be equal to B if the difference is less than 0.001".

As you say, if you want a 'bit width' slot then use the centerline tool.
